// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: public.proto

package public

import (
	"context"
	desc "disputes/pkg/api/public"

	"github.com/pkg/errors"
)

func (i *Implementation) Health(ctx context.Context, req *desc.HealthRequest) (*desc.HealthResponse, error) {
	return nil, errors.New("Health not implemented")
}
