// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: public.proto

package public

import (
	"context"
	desc "disputes/pkg/api/public"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestImplementation_Health(t *testing.T) {
	api := NewPublicAPI()
	_, err := api.Health(context.Background(), &desc.HealthRequest{})

	require.NotNil(t, err)
	require.Equal(t, "Health not implemented", err.Error())
}
