// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: public.proto

package public

import (
	"context"
	desc "disputes/pkg/api/public"
	"github.com/gogo/protobuf/types"
)

func (i *Implementation) Health(ctx context.Context, _ *types.Empty) (*desc.HealthResponse, error) {
	return &desc.HealthResponse{
		Status: "success",
	}, nil
}
