// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: public.proto

package public

import (
	config "disputes/internal/config/app"
	desc "disputes/pkg/api/public"

	"github.com/utrack/clay/v2/transport"
)

type Implementation struct {
	Host int
}

// NewPublicAPI create new Implementation
func NewPublicAPI(cfg *config.Config) *Implementation {
	return &Implementation{Host: cfg.HostPublicAPI}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return desc.NewPublicAPIServiceDesc(i)
}
