// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: public.proto

package public

import (
	desc "disputes/pkg/api/public"

	"github.com/utrack/clay/v2/transport"
)

type Implementation struct{}

// NewPublicAPI create new Implementation
func NewPublicAPI() *Implementation {
	return &Implementation{}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return desc.NewPublicAPIServiceDesc(i)
}
