// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: admin.proto

package admin

import (
	config "disputes/internal/config/app"
	desc "disputes/pkg/api/admin"

	"github.com/utrack/clay/v2/transport"
)

type Implementation struct {
	Host int
}

// NewAdminAPI create new Implementation
func NewAdminAPI(cfg *config.Config) *Implementation {
	return &Implementation{Host: cfg.HostAdminAPI}
}

// GetDescription is a simple alias to the ServiceDesc constructor.
// It makes it possible to register the service implementation @ the server.
func (i *Implementation) GetDescription() transport.ServiceDesc {
	return desc.NewAdminAPIServiceDesc(i)
}
