// Code generated by protoc-gen-goclay, but your can (must) modify it.
// source: admin.proto

package admin

import (
	"context"
	"github.com/gogo/protobuf/types"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestImplementation_Health(t *testing.T) {
	api := NewAdminAPI()
	_, err := api.Health(context.Background(), &types.Empty{})

	require.NotNil(t, err)
	require.Equal(t, "Health not implemented", err.Error())
}
